services:
  geocontext:
    image: geocontext
    build:
      context: .
      args:
      - http_proxy
      - https_proxy
    environment:
      - PUBLIC_URL=${PUBLIC_URL:-http://localhost:3000}
      - http_proxy
      - https_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
    ports:
    - ${APP_PORT:-3000}:3000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 256M
    restart: unless-stopped
