openapi: 3.1.0
info:
  title: geocontext
  description: |-
    An **experimental** API providing spatial context for LLM.
  license:
    name: MIT
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.3.0

#servers:
#  - url: https://geocontext.quadtreeworld.net

externalDocs:
  description: GitHub repository
  url: https://github.com/mborne/geocontext#readme

tags:
  - name: altitude
    description: Altitude
  - name: admin-units
    description: Unités administratives
  - name: urbanisme
    description: Géoportail de l'Urbanisme

paths:

  /api/gpf/altitude:
    get:
      tags:
        - altitude
      summary: Provides the altitude of a location given by its longitude and latitude Géoplateforme (altimetrie service)
      description: Provides the altitude of a location given by its longitude and latitude.
      operationId: getAltitude
      parameters:
        - in: query
          name: lon
          required: true
          description: the longitude of a location
          example: 6.869433
          schema:
            type: number
        - in: query
          name: lat
          required: true
          description: the latitude of a location
          example: 45.923697
          schema:
            type: number
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AltitudeResponse'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
        '500':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


  /api/gpf/adminexpress:
    get:
      tags:
        - admin-units
      summary: Provides administrative units (french communes, departements, regions,...) for a location given by its longitude and latitude using Géoplateforme (WFS, ADMINEXPRESS-COG.LATEST).
      description: |
        Find the following french type of administrative units for a location given by its longitude and latitude :
          * commune 
          * canton
          * collectivite_territoriale
          * epci
          * departement
          * region 
          * arrondissement
      operationId: getAdminUnitsFromAdminExpress
      parameters:
        - in: query
          name: lon
          required: true
          description: the longitude of a location
          example: 6.869433
          schema:
            type: number
        - in: query
          name: lat
          required: true
          description: the latitude of a location
          example: 45.923697
          schema:
            type: number
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AdminExpressItem'

        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
        '500':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


  /api/gpf/parcellaire-express:
    get:
      tags:
        - admin-units
      summary: "Renvoie les informations cadastrales pour une position donnée par sa longitude et sa latitude à l'aide du WFS Géoplateforme (CADASTRALPARCELS.PARCELLAIRE_EXPRESS)."
      description: |
        Renvoie les types ci-après correspondant à la position :
          * arrondissement : L'arrondissement municipal (Paris, Lyon et Marseille uniquement)
          * commune : La commune
          * feuille : La feuille, la planche ou la division cadastrale
          * localisant : Un localisant parcellaire
          * parcelle : La parcelle
          * subdivision_fiscale : La subdivision fiscale
      operationId: getParcellaireExpress
      parameters:
        - in: query
          name: lon
          required: true
          description: La longitude
          example: 6.869433
          schema:
            type: number
        - in: query
          name: lat
          required: true
          description: La latitude
          example: 45.923697
          schema:
            type: number
      responses:
        '200':
          description: liste des éléments éléments trouvées
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ParcellaireExpressItem'

        '400':
          description: mauvaise requête
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
        '500':
          description: erreur système
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'



  /api/gpu/urbanisme:
    get:
      tags:
        - urbanisme
      summary: "Renvoie les informations du document d'urbanisme (PLU, POS, CC, PSMV) pour une position donnée par sa longitude et sa latitude à l'aide du WFS Géoplateforme (wfs_du et wfs_scot)."
      description: |
        Renvoie les informations du document d'urbanisme (PLU, POS, CC, PSMV) pour une position donnée par sa longitude et sa latitude à l'aide du WFS Géoplateforme (wfs_du et wfs_scot).
      operationId: getGpfUrbanisme
      parameters:
        - in: query
          name: lon
          required: true
          description: La longitude
          example: 6.869433
          schema:
            type: number
        - in: query
          name: lat
          required: true
          description: La latitude
          example: 45.923697
          schema:
            type: number
      responses:
        '200':
          description: liste des éléments parcelles trouvées
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UrbanismeItem'

        '400':
          description: mauvaise requête
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
        '500':
          description: erreur système
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'




components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "An error occurred"
    BadRequestResponse:
      type: object
      properties:
        message:
          type: string
          example: "Invalid request parameters"


    AltitudeResponse:
      type: object
      properties:
        lon:
          type: number
          description: The longitude of the point (input)
        lat:
          type: number
          description: The latitude of the point (input)
        altitude:
          type: number
          description: The altitude of the point (output)

    AdminExpressItem:
      type: object
      properties:
        type:
          type: string
          description: The type of the administrative unit
          examples: [commune, departement, region]
        id:
          type: string
          description: The BDTOPO identifier
          example: COMMUNE_0000000009750652
        bbox:
          schema:
            $ref: '#/components/schemas/BoundingBox'
        nom:
          type: string
          description: The name of the administrative unit
          example: "Chamonix-Mont-Blanc"
        nom_m:
          type: string
          description: The upper case name of the administrative unit
          example: "CHAMONIX-MONT-BLANC"
        insee_com:
          type: string
          description: INSEE code of the commune
          example: "74056"
        insee_dep:
          type: string
          description: INSEE code of the departement
          example: "74"
        insee_reg:
          type: string
          description: INSEE code of the region
          example: "74"
        statut:
          type: string
          description: Status of the commune
          example: "Commune simple"
        population:
          type: number
          description: Population of the commune (not available for departement and region)
          example: 8642
        # commune specific, not documented :
        #"insee_can": "10",
        #"insee_arr": "2",
        #"siren_epci": "200023372"

    ParcellaireExpressItem:
      type: object
      externalDocs:
        description: Parcellaire Express (PCI) - Descriptif de contenu
        url: https://geoservices.ign.fr/sites/default/files/2022-06/DC_Parcellaire_Express_%28PCI%29_1-1.pdf
      properties:
        id:
          type: string
          description: Identifiant technique
        type:
          type: string
          description: classe de l'objet
          enum:
            - arrondissement
            - commune
            - feuille
            - subdivision_fiscale
            - parcelle
            - localisant
        bbox:
          schema:
            $ref: '#/components/schemas/BoundingBox'
        distance:
          type: number
          distance: La distance en degrée entre l'objet et la position.
          minimum: 0
        source:
          type: string
          example: Géoplateforme (WFS, CADASTRALPARCELS.PARCELLAIRE_EXPRESS)
        code_dep:
          type: string
          description: Code INSEE du département.
          example: "74"
        code_com:
          type: string
          description: Code de la commune.
          example: 056
        nom_com:
          type: string
          description: Nom de la commune.
          example: Chamonix-Mont-Blanc
        code_insee:
          type: string
          description: Numéro INSEE de la commune.
          example: "74056"
        feuille:
          type: integer
          description: Numéro de la feuille cadastrale.
          example: 7
        section:
          type: string
          description: Numéro de la section cadastrale.
        com_abs:
          type: string
          description: Ancien code de la commune en cas de fusion de communes.
          example: "000"
        code_arr:
          type: string
          description: Code de l’arrondissement.
          example: "000"
        idu:
          type: string
          description: Identifiant de la parcelle cadastrale.
          example: "740560000G4353"
        numero:
          type: string
          description: Numéro de la parcelle cadastrale.
          example: "4353"
        contenance:
          type: integer
          minimum: 0
          description: Superficie extraite de MAJIC exprimée en m².
          example: 178
        echelle:
          type: string
          description: Dénominateur de l’échelle principale du plan cadastral.
          example: 500
        edition:
          type: string
          format: date
          description: Numéro d’édition de la feuille cadastrale
          example: "2023-07-01"
      required:
        - id
        - type
        - bbox
        - nom_com
        - code_dep
        - code_insee
        - source


    UrbanismeItem:
      type: object
      properties:
        id:
          type: string
          description: Identifiant technique de l'objet
        type:
          type: string
          description: Identifiant du type de l'objet
          enum:
            - scot
            - document
            - info_pct
            - info_lin
            - info_surf
            - prescription_pct
            - prescription_lin
            - prescription_surf
        bbox:
          schema:
            $ref: '#/components/schemas/BoundingBox'
        distance:
          type: number
          distance: La distance en degrée entre l'objet et la position.
          minimum: 0
        source:
          type: string
          example: Géoplateforme - (WFS Géoportail de l'Urbanisme)
        gid:
          type: number
          description: Identifiant technique de l'objet
          example: 2905619
        gpu_doc_id:
          type: string
          description: Identifiant unique du document sur le GpU
          example: 398a91a8349876bc9f08c2830347b4f1
        partition:
          type: string
          description: Identifiant stable du document d'urbanisme sur le GpU
          example: DU_74056
        # TODO : complete
      required:
        - id
        - type
        - bbox
        - source

    #--------------------------------------------------------------------------
    # helper types
    #--------------------------------------------------------------------------
    BoundingBox:
      description: "Geo-spatial bounding box."
      type: array
      items:
        type: number
      minItems: 4
      maxItems: 4
